%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Falk/Dropbox/PhD/Metacognitive RL/MCRL/experiments/data/human/1C.0/trials.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/11/07 15:57:01

%% Initialize variables.
filename = '/Users/Falk/Dropbox/PhD/Metacognitive RL/MCRL/experiments/data/human/1C.0/trials.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: text (%q)
%   column5: text (%q)
%	column6: double (%f)
%   column7: double (%f)
%	column8: text (%q)
%   column9: double (%f)
%	column10: double (%f)
%   column11: text (%q)
%	column12: text (%q)
%   column13: text (%q)
%	column14: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%q%q%f%f%q%f%f%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
pid1 = dataArray{:, 2};
info_cost1 = dataArray{:, 3};
PR_type1 = dataArray{:, 4};
message1 = dataArray{:, 5};
trial_index1 = dataArray{:, 6};
trial_id1 = dataArray{:, 7};
delays1 = dataArray{:, 8};
score1 = dataArray{:, 9};
n_click1 = dataArray{:, 10};
clicks1 = dataArray{:, 11};
click_times1 = dataArray{:, 12};
path1 = dataArray{:, 13};
action_times1 = dataArray{:, 14};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;