%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Falk/Dropbox/PhD/Metacognitive RL/MCRL/experiments/data/human/0.992/participants.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/10/28 19:00:45

%% Initialize variables.
filename = '/Users/Falk/Dropbox/PhD/Metacognitive RL/MCRL/experiments/data/human/0.992/participants.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%q)
%	column2: double (%f)
%   column3: double (%f)
%	column4: text (%q)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: text (%q)
%   column9: text (%q)
%	column10: double (%f)
%   column11: text (%q)
%	column12: double (%f)
%   column13: text (%q)
%	column14: double (%f)
%   column15: text (%q)
%	column16: text (%q)
%   column17: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%f%f%q%f%f%f%q%q%f%q%f%q%f%q%q%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
PR_type1 = dataArray{:, 1};
bonus = dataArray{:, 2};
bonus_rate = dataArray{:, 3};
completed = dataArray{:, 4};
condition = dataArray{:, 5};
delay_hours = dataArray{:, 6};
delay_window = dataArray{:, 7};
feedback1 = dataArray{:, 8};
frequencyOfFB = dataArray{:, 9};
info_cost1 = dataArray{:, 10};
message1 = dataArray{:, 11};
pid1 = dataArray{:, 12};
q_weights = dataArray{:, 13};
score1 = dataArray{:, 14};
test_idx = dataArray{:, 15};
time_limit = dataArray{:, 16};
version1 = dataArray{:, 17};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;