#! /bin/sh

if [ $# -eq 0 ]; then
        echo "syntax:  matlab_background <command> [<outputfile>]"
        exit
fi

unset DISPLAY
export DISPLAY

hostname
echo "Running matlab silently..."
echo "  matlab command: $1"


if [ $# -eq 1 ]; then
        echo "  no output file specified, using stdout"
        matlab_nojvm 2>&1 << EOF 
$1
EOF

else
        echo "  output file: $2"
        
        matlab >& $2 << EOF 
$1
EOF

fi

# clean up temp files if they're from the queue
echo ""
echo "$QUEUEID $TMP"
if [ "" != "$QUEUEID" ]; then
    if [ "$TMP" == "/tmp/$QUEUEID" ]; then
        \rm -R $TMP
    fi
fi
